name: template
services:
  db:
    image: postgres:17-alpine
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"


volumes:
  postgresql-data:
